name: go test check

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    name: Run go test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...  # Run all tests in current directory and all subdirectories